export enum DomainEvent {
  QUOTE_SENT = 'QUOTE_SENT',
  QUOTE_APPROVED = 'QUOTE_APPROVED',
  JOB_STARTED = 'JOB_STARTED',
  PART_ORDERED = 'PART_ORDERED',
  PART_RECEIVED = 'PART_RECEIVED',
  JOB_COMPLETED = 'JOB_COMPLETED',
  INVOICE_GENERATED = 'INVOICE_GENERATED',
  PAYMENT_RECORDED = 'PAYMENT_RECORDED',
  VEHICLE_READY = 'VEHICLE_READY'
}
